name: Deployment to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Build client
      run: |
        cd client
        npm install
        npm run build

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Build server
      run: |
        cd server
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o executable

    # - name: Setup SSH
    #   uses: webfactory/ssh-agent@v0.5.3
    #   with:
    #     ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to VPS
      env:
        HOST: hazemkrimi.tech
        USER: deploy
      run: |
        mkdir -p ~/.ssh
        echo $DEPLOY_SSH_KEY > ~/.ssh/id_deploy
        chmod 600 ~/.ssh/id_deploy

        echo "Host *" > ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

        ssh-keyscan -H $HOST > ~/.ssh/known_hosts

        scp -r client/build $USER@$HOST:/var/www/touch-programming.hazemkrimi.tech/public
        scp server/executable $USER@$HOST:/var/www/touch-programming.hazemkrimi.tech/api
